fn_args_layout = "Vertical"
force_multiline_blocks = true
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 80
merge_imports = true
reorder_impl_items = true
struct_lit_single_line = false
# trailing_comma = "Always"
use_small_heuristics = "Off"